### ISSUE TITLE
Incorrect tab count when Close Other Tabs/Close Tabs to the Right closes more than one tab

### ISSUE THREAD

**Issue by spideymouse** [Lej77/tab-count-in-window-title#1]
When clicking Close Other Tabs or Close Tabs to the Right closes more than one tab, the Tab Count only reduces by one, instead of reducing to the remaining number of tabs.

**Comment by Lej77** [comment]
Thank you for bringing this to my attention. I have released a new version (v3.0) of the extension that should fix this issue.
