### ISSUE TITLE
[Request] Display current tab #

### ISSUE THREAD

**Issue by AeliusSaionji** [Lej77/tab-count-in-window-title#3]
Where the tab furthest left is `1` and the second tab `2` and so on, I'd like to be able to see where I sit in my stack. If I have 4 tabs open and I'm currently looking at the 3rd tab, I'd want my window title to read `[3/4]`.

Thanks!

**Comment by Lej77** [comment]
Thanks for the idea, I'll take a look at this when I get time!

**Comment by Lej77** [comment]
Hello! Its been a while but I have released a new version of the extension (v5.0) that has a `%ActiveTabIndex%` placeholder that should do what you want. You could use a preface format like `[%ActiveTabIndex%/%TabCount%] %IfWindowName(%WindowName% | ,)%` to get your desired outcome.

**Comment by AeliusSaionji** [comment]
Thanks!
